### PR TITLE
[10.0] [BACKPORT] foreign currencies

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
@SimoRubi here such a first approach to a back port from my work in v11 to you branch.

### CODE REVIEW

**Comment by SimoRubi** [comment]
Thanks for your effort @hveficent, this looks good

**Comment by HviorForgeFlow** [comment]
We have to discuss about account.group feature I added, because in v10 didn't exist, so it could be done usigin another workaround instead of adding that class as custom, but for the moment we might keep it this way.

OPS sorry, seems has been already deleted, I think I did already

**Comment by SimoRubi** [comment]
Yes I have seen it maybe in your first commit here, but in the current commit no trace of that, so I merged.

**Comment by HviorForgeFlow** [comment]
It has been asked to me to backport also dynamic reports, I think it will be ready tomorrow.

**Pull request merged**
